# Generated by Django 3.2 on 2021-05-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
