# Generated by Django 3.2 on 2021-05-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_bill_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cardnumber',
            field=models.BigIntegerField(),
        ),
    ]
